app_web:
    resource: '@AppBundle/Controller/Web'
    type: annotation

app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

